# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'AICamera-ObjC' do
	pod 'PytorchExpObjC', :git=>'https://github.com/xta0/PytorchExpObjC.git' ,:branch => 'master'
end
